CREATE SCHEMA app_meta;
CREATE SCHEMA identity;
CREATE SCHEMA tenancy;
CREATE SCHEMA audit;
DO $$ BEGIN CREATE ROLE barber_owner NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE barber_runtime LOGIN PASSWORD 'barber_runtime' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

